version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\aphros\src
    steps:
      - checkout:
          path: C:\Users\circleci\aphros
      - run:
         name: cl
         shell: cmd.exe
         command: |
            call ..\.circleci\main.bat
